<?php

namespace AppBundle\Repository;

/**
 * WatchfloorTrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchfloorTrackingRepository extends \Doctrine\ORM\EntityRepository
{
}
