app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"